name: Check
on: [push, pull_request]
permissions:
  contents: read
jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: swift test
      - run: bash scripts/build.sh
